trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'hello world'

- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'

- task: Npm@1
  displayName: eslint
  inputs:
    command: 'custom'
    customCommand: 'run lint'

- task: Docker@2
  displayName: 'Build and push frontend'
  inputs:
    containerRegistry: 'gustav87 Docker Hub'
    repository: 'gustav87/react1-frontend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'

